[package]
name = "ockam_message"
version = "0.1.0"
authors = ["Ockam Developers"]
edition = "2018"

[lib]
crate-type = ["rlib"]

[dependencies]
serde_bare = "0.3.0"
serde = {version = "1.0.120", features = ["derive"]}
serde_json = "1.0.61"
url = "2.2.0"
hex = "0.4.2"

